import type { Plugin } from 'vite'
import { readFile, writeFile } from 'node:fs/promises'
import path from 'node:path'

/**
 * Dev-only endpoint behind the mobile tuner overlay (`src/dev/mobileTuner.ts`).
 *
 * The tuner sends the whole tweak set; this writes it to disk twice — once as
 * JSON, which is the state the tuner reads back on reload, and once as CSS,
 * which is what the page actually renders. Generating the CSS here rather than
 * letting the browser post CSS text is what keeps the file trustworthy: the
 * property names and values are checked against a whitelist on this side, so
 * nothing the overlay does can write a broken rule into the stylesheet.
 */

const JSON_FILE = 'src/mobile-tweaks.json'
const CSS_FILE = 'src/mobile-tweaks.css'

/** Layout properties the tuner is allowed to set. Deliberately narrow.
 *
 *  `translate` and `scale` are the movement primitives rather than `transform`
 *  because GSAP animates `transform` through inline styles, which no stylesheet
 *  rule can outrank. `translate`/`scale` are separate CSS properties that
 *  compose with it, so a tuned position survives the animations. */
const ALLOWED_PROPS = new Set([
  'translate',
  'scale',
  'font-size',
  'line-height',
  'letter-spacing',
  'width',
  'height',
  'padding',
  'gap',
  'margin-top',
  'margin-bottom',
  'display',
])

/** Values are numbers with units, or a couple of keywords — nothing else. A
 *  brace, semicolon or comment opener would let a value escape its rule. */
const VALUE_OK = /^[-\d.a-z%\s]+$/i
const SELECTOR_OK = /^[-\w.\s>:()#\[\]="',]+$/

const isClean = (s: string) => !/[{};@\\]|\/\*/.test(s)

type Tweaks = Record<string, Record<string, string>>

function sanitise(input: unknown): Tweaks {
  const out: Tweaks = {}
  if (!input || typeof input !== 'object') return out

  for (const [selector, decls] of Object.entries(input as Record<string, unknown>)) {
    if (!SELECTOR_OK.test(selector) || !isClean(selector)) continue
    if (!decls || typeof decls !== 'object') continue

    const kept: Record<string, string> = {}
    for (const [prop, value] of Object.entries(decls as Record<string, unknown>)) {
      if (!ALLOWED_PROPS.has(prop)) continue
      if (typeof value !== 'string') continue
      const trimmed = value.trim()
      if (!trimmed || !VALUE_OK.test(trimmed) || !isClean(trimmed)) continue
      kept[prop] = trimmed
    }
    // A selector whose declarations were all cleared drops out entirely, which
    // is how "reset this element" reaches the file.
    if (Object.keys(kept).length) out[selector] = kept
  }
  return out
}

function toCss(tweaks: Tweaks): string {
  const header = `/* Generated by the mobile tuner — see the README, "Adjusting the mobile
   layout by hand". Edit through the tuner rather than here; every Save
   rewrites this whole file.

   Every rule sits inside the max-width: 700px query, so nothing in this file
   can reach the desktop layout. The :root prefix is only there for weight —
   it lets a tuned value outrank the hand-written mobile rule it replaces. */\n\n`

  const selectors = Object.keys(tweaks).sort()
  if (!selectors.length) {
    return header + `@media screen and (max-width: 700px) {\n  /* Nothing tuned yet. */\n}\n`
  }

  const body = selectors
    .map((selector) => {
      const decls = Object.entries(tweaks[selector])
        .sort(([a], [b]) => a.localeCompare(b))
        .map(([prop, value]) => `    ${prop}: ${value};`)
        .join('\n')
      return `  :root ${selector} {\n${decls}\n  }`
    })
    .join('\n\n')

  return `${header}@media screen and (max-width: 700px) {\n${body}\n}\n`
}

function readBody(req: NodeJS.ReadableStream): Promise<string> {
  return new Promise((resolve, reject) => {
    let raw = ''
    req.on('data', (chunk) => {
      raw += chunk
      // A tweak set is a few kB at most; anything larger is a bug or a probe.
      if (raw.length > 512_000) reject(new Error('payload too large'))
    })
    req.on('end', () => resolve(raw))
    req.on('error', reject)
  })
}

export function mobileTweaks(): Plugin {
  return {
    name: 'mobile-tweaks',
    apply: 'serve',
    configureServer(server) {
      const root = server.config.root
      const jsonPath = path.join(root, JSON_FILE)
      const cssPath = path.join(root, CSS_FILE)

      server.middlewares.use('/__mobile-tweaks', async (req, res) => {
        res.setHeader('Content-Type', 'application/json')

        if (req.method === 'GET') {
          try {
            res.end(await readFile(jsonPath, 'utf8'))
          } catch {
            res.end('{}')
          }
          return
        }

        if (req.method === 'POST') {
          try {
            const tweaks = sanitise(JSON.parse(await readBody(req)))
            await writeFile(jsonPath, JSON.stringify(tweaks, null, 2) + '\n')
            await writeFile(cssPath, toCss(tweaks))
            res.end(JSON.stringify({ ok: true, selectors: Object.keys(tweaks).length }))
          } catch (err) {
            res.statusCode = 400
            res.end(JSON.stringify({ ok: false, error: String(err) }))
          }
          return
        }

        res.statusCode = 405
        res.end(JSON.stringify({ ok: false }))
      })
    },
  }
}
